version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: lamp_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db # you need to change hostname in config.php for local docker development
      - MYSQL_USER=TheBeast
      - MYSQL_PASSWORD=WeLoveCOP4331
      - MYSQL_DATABASE=COP4331

  db:
    image: mysql:8.0
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: COP4331
      MYSQL_USER: TheBeast
      MYSQL_PASSWORD: WeLoveCOP4331
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
