version: '3.8'

services:
  web:
    build: .
    container_name: lamp_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=TheBeast
      - MYSQL_PASSWORD=WeLoveCOP4331
      - MYSQL_DATABASE=project_dev

  db:
    image: mysql:8.0
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_dev
      MYSQL_USER: TheBeast
      MYSQL_PASSWORD: WeLoveCOP4331
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: